On branch new_branch
Programming-with-Pouriya-2021/tabdil pull request #7
Opened 2022-03-08 08:01 UTC by kavehbarzegar

new file:   temperature.py
adding a feature to the Project

2022-03-08 15:51 UTC, pouriya commented
CI has failed!  
Se the details and fix the issue please.

2022-03-09 15:32 UTC, kavehbarzegar commented
I corrected mistakes

2022-03-09 16:08 UTC, pouriya requested changes

2022-03-09 16:08 UTC, pouriya commented on tabdil/temperature.py
>      unit_tem = tem_unit[0].lower()
what is it for?

2022-03-09 16:21 UTC, kavehbarzegar commented on tabdil/temperature.py
>      unit_tem = tem_unit[0].lower()
it helps to be sure unit_tem is lower case cause I used lower cases in my code

2022-03-09 17:04 UTC, kavehbarzegar commented on tabdil/temperature.py
>      unit_tem = tem_unit[0].lower()
I fixed it, it should be deleted

2022-03-09 18:41 UTC, pouriya commented
CI failed again!

2022-03-10 13:41 UTC, pouriya commented
ping

2022-03-25 09:54 UTC, closed without merging